FROM alpine:3.4

COPY docker/zotonic.config /etc/zotonic/zotonic.config
COPY docker/erlang.config.sed /opt/zotonic/docker/erlang.config.sed
COPY priv/erlang.config.in /opt/zotonic/priv/erlang.config.in

WORKDIR /opt/zotonic

RUN sed -f docker/erlang.config.sed priv/erlang.config.in > /etc/zotonic/erlang.config

RUN apk add --no-cache ca-certificates bash curl make gcc musl-dev g++ bsd-compat-headers git imagemagick inotify-tools wget \
    && apk add --no-cache --repository http://dl-3.alpinelinux.org/alpine/edge/community/ \
        erlang erlang-inets erlang-compiler erlang-crypto erlang-mnesia erlang-ssl erlang-stdlib erlang-public-key erlang-tools erlang-dev erlang-asn1 erlang-syntax-tools erlang-eunit erlang-parsetools erlang-snmp erlang-sasl erlang-xmerl erlang-erl-interface

VOLUME /opt/zotonic
VOLUME /etc/zotonic
