#!/usr/bin/env bash
#
# Copyright 2011 Lloyd R. Prentice
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-start
#

#
# The heart restart loop protection below was taken from yaws startup script.
# For more information see: http://steve.vinoski.net/blog/2009/02/22/controlling-erlangs-heart/
#

cd $ZOTONIC

now=`date -u +%s`

if [ "$HEART" = true ]; then
    # we were restarted by heart, make sure we haven't reached our restart count
    # if we get 5 restarts within 60 seconds, we exit completely
    timediff=`expr $now - $ZOTONIC_HEART_START`
    if [ $timediff -le 60 ]; then
        if [ $ZOTONIC_HEART_RESTARTS -eq 5 ]; then
            # 5 restarts attempted within 60 seconds, exiting
	    exit 1
	else
            # we haven't reached the restart max count yet, but we're still
            # within the 60 second window so increment the counter
            # but keep the same start time
            restarts=`expr $ZOTONIC_HEART_RESTARTS + 1`
            starttime=$ZOTONIC_HEART_START
        fi
    else
        # the previous restart was outside our 60 second window,
        # so reset both the start time and the restart counter
        restarts=1
        starttime=$now
    fi
else
    restarts=1
    starttime=$now

    # Only build zotonic the first time, not for restarts
    echo  "Starting zotonic $SNAME@$HOSTNAME" 
    if make --version 2>&1 | grep "^GNU Make" >& /dev/null
    then
      MAKE=make
    else
      MAKE=gmake
    fi
    ${MAKE} >/dev/null
fi

ENV=`which env`
HEART_COMMAND="${ENV} HEART=true ZOTONIC_HEART_RESTARTS=$restarts ZOTONIC_HEART_START=$starttime $ZOTONIC_BIN/zotonic start"
export HEART_COMMAND

$ERL -env ERL_MAX_PORTS $MAX_PORTS -pa $PA -name $SNAME@$HOSTNAME -boot start_sasl -config $ZOTONIC/priv/erlang.config -heart -detached -s zotonic
