#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic-createdb [site_name]
%%

-export([main/1]).

-define(NODENAME, "zotonic001").
-define(ZOTONIC, get_zotonic_path()).
-define(NODEHOST, get_node_host()).

get_zotonic_path() ->
    {ok, CurrentDir} = file:get_cwd(),
    _Dir = CurrentDir.

get_node_host() ->
    {ok, HostName} = inet:gethostname(),
    _NodeHost = HostName.

load_mod_paths() ->
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_launcher/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_core/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_stdlib/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/lager/ebin")).

main([Site]) ->
    load_mod_paths(),
    SiteName = list_to_atom(Site),

    case string:is_empty(Site) of
        true  ->
            io:format("USAGE: ~s", [list_to_atom(escript:script_name())]),
            io:format("USAGE: See ZotonicCommands.txt");
        false ->
            net_kernel:start([zotonic_createdb, shortnames]),
            erlang:set_cookie(node(), erlang:get_cookie()),
            Target = list_to_atom(?NODENAME ++ "@" ++ ?NODEHOST),

            Res = rpc:call(Target, z_db, prepare_database, [SiteName]),
            io:format("~p~n", [Res])
    end.
