#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic stopsite [site_name]
%%

-export([main/1]).

-include("zotonic_escript_helper.hrl").

main([Site]) ->
    zotonic_setup:require_zotonic_running(),
    case Site of
        ""  ->
            io:format("USAGE: ~p [site_name] ~n", [escript:script_name()]);
        _ ->
            io:format("Stopping site ~p on zotonic ~p@~p", [Site, ?NODENAME, ?NODEHOST]),
            z_sites_manager:stop(Site)
    end.
