#!/usr/bin/env bash
#
# Copyright 2011 Lloyd R. Prentice
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-debug
#

cd $ZOTONIC

# Allow for custom SNAME as extra argument. If so, we move the ports
if [ "$1" != "" ]; then
    export SNAME=$1;
    NR=`echo $SNAME|sed -e 's/[^0-9]//g'`;
    echo $NR;
    export ZOTONIC_PORT=`echo ${ZOTONIC_PORT:=8000}+$NR|bc`
    export ZOTONIC_PORT_SSL=`echo ${ZOTONIC_PORT_SSL:=443}+$NR|bc`
    export ZOTONIC_SMTP_LISTEN_PORT=`echo ${ZOTONIC_SMTP_LISTEN_PORT:=2525}+$NR|bc`
    echo "Starting Zotonic using custom port configuration."
fi

$ERL -env ERL_MAX_PORTS $MAX_PORTS +P 10000000 +K true -pa $PA -name $SNAME@$HOSTNAME -boot start_sasl -config $ZOTONIC/priv/erlang.config -sasl errlog_type error -s zotonic 
