#!/usr/bin/env bash
#
# Copyright 2011 Arjan Scherpenisse <arjan@scherpenisse.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-compilefile <file> [file..]
#

function usage {
    echo "Usage: `basename $0` [files...]" 1>&2
    echo 1>&2
    exit 1
}

if [ "$*" = "" ]; then
    usage
fi

for FILE in $*; do
    if [ "${FILE::1}" != "/" ]; then
        FILE="`pwd`/$FILE"
    fi

    F=$(echo $FILE|sed -e "s!^$ZOTONIC/!!")
    if [ ! -e "$ZOTONIC/$F" ]; then
        echo "$FILE is not under the Zotonic basedir." 1>&2
        echo 1>&2
        exit 1
    fi
    echo "Compiling $F"
    (cd $ZOTONIC; $ERL -noshell -pa $PA $NAME_ARG ${NODENAME}_compile@$HOSTNAME -run make files "$F" -s erlang halt)
done
