#!/usr/bin/env bash
#
# Copyright 2011 Lloyd R. Prentice
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-start
#

cd $ZOTONIC
if [ ! -f $ZOTONIC_PIDFILE ]; then
    echo Not Running
    exit 1
fi

PID=`cat $ZOTONIC_PIDFILE`
if ps -p $PID >&-
then
    echo "\
Running: $SNAME@$HOSTNAME

Sites Status:
============="
    $ERL -noshell -pa $PA -name ${SNAME}_stop@$HOSTNAME -s zotonic status $SNAME@$HOSTNAME -s init stop
    echo
    exit 0
else
    echo "Not Running (process '$PID' may have crashed or been killed)"
    exit 1
fi 
