#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic-crateschema [schema_name]
%%

-export([main/1]).

-include("zotonic_escript_helper.hrl").

main([]) ->
    ErlangConfig = list_to_atom(zotonic_setup:find_config_arg("erlang.config")),
    ZotonicConfig = list_to_atom(zotonic_setup:find_config_arg("zotonic.config")),

    ZotonicAppFile = ?ZOTONIC ++ "/_build/default/lib/zotonic/ebin/zotonic.app",

    case filelib:is_file(ZotonicAppFile) of
        true ->
            halt();
        false ->
            io:format("Building Zotonic for the first time."),
            os:cmd(?MAKE)
    end,

    zotonic_setup:require_zotonic_not_running(),

    case file:set_cwd(?ZOTONIC) of
         ok ->
             os:cmd(?ERL ++ " -env ERL_MAX_PORTS " ++ ?MAX_PORTS ++ " +P " ++ ?MAX_PROCESSES ++ " +k " ++
                 ?KERNEL_POLL + " -pa " ++ ?PA ++ " " ++ ?NAME_ARG ++ " " ++ ?NODENAME ++ "@" ++ ?NODEHOST ++
                 " -boot start_sasl " ++ ErlangConfig ++ " " ++ ZotonicConfig ++ " -sasl errlog_type error -s zotonic")
    end.
