#!/usr/bin/env bash
#
# Copyright 2011 Lloyd R. Prentice
# Copyright 2012 Andreas Stenius
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-dropschema [schema_name]
#

SCHEMA=$1

if [ -f "$HOME/.zotonic-defaults" ]; then
    source "$HOME/.zotonic-defaults"
fi

if [ ! "$SCHEMA" ]
then
	echo USAGE: `basename $0` [schema_name] 1>&2
	echo USAGE: See ZotonicCommands.txt 1>&2
else
	# Drop the database schema
	sed s/%schema/$SCHEMA/g \
		< $ZOTONIC_SCRIPTS/helpers/zotonic-dropschema_sql.in \
		| ${PSQL:=psql}
fi
