#!/usr/bin/env bash
#
# Copyright 2016 Arjan Scherpenisse
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. $ZOTONIC_SCRIPTS/helpers/zotonic_setup

require_zotonic_not_running
set -e

EBIN_DIR=_build/default/lib/zotonic/ebin

if [ "$1" == "" ]; then
    echo "Usage: zotonic sitetest <sitename>" 1>&2
    echo 1>&2
    exit 1
fi

SITE=$1

echo
echo "Running sitetest for site: $SITE"
echo

# Run the sitetests
$ERL +P 10000000 +K true -pa $PA $NAME_ARG ${NODENAME}_sitetest@$NODEHOST $(find_config_arg erlang.config) $(find_config_arg zotonic.config) -noshell -boot start_sasl -sasl errlog_type error -s zotonic -eval "timer:sleep(8000),init:stop(case z_sitetest:run($SITE) of error -> 1; ok -> 0 end)"
EXIT=$?
