#!/usr/bin/env bash
#
# Copyright 2011 Lloyd R. Prentice
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-snapshot [site_name]
#

SITE=$1

if [ ! $SITE ]
then
	echo USAGE: $0 [site_name] 1>&2
	echo USAGE: See ZotonicCommands.txt 1>&2
else
	mkdir -p $SITES/$SITE/files/snapshot
	pg_dump zotonic_$SITE \
			> $SITES/$SITE/files/snapshot/zotonic_$SITE.sql

	pushd $SITES/$SITE > /dev/null
	hg init
	hg add
	hg commit -m "Content Snapshot"
	popd > /dev/null
fi
