#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic stop
%%

-export([main/1]).

-define(NODENAME, "zotonic001").
-define(ZOTONIC, get_zotonic_path()).
-define(NODEHOST, get_node_host()).

get_zotonic_path() ->
    {ok, CurrentDir} = file:get_cwd(),
    _Dir = CurrentDir.

get_node_host() ->
    {ok, HostName} = inet:gethostname(),
    _NodeHost = HostName.

load_mod_paths() ->
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_launcher/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_core/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/zotonic_stdlib/ebin")),
    code:add_pathz(string:concat(?ZOTONIC, "/_build/default/lib/lager/ebin")).

main([]) ->
    load_mod_paths(),
    net_kernel:start([zotonic_stop, shortnames]),
    erlang:set_cookie(node(), erlang:get_cookie()),
    Target = list_to_atom(?NODENAME ++ "@" ++ ?NODEHOST),
    io:format("Stopping Zotonic ~p..", [Target]),
    case net_adm:ping(Target) of
        pong  ->
            rpc:call(Target, init, stop, []),
            io:format("Ok~n");
        pang ->
            halt()
    end.
