#!/usr/bin/env bash
#
# Copyright 2015 Marc Worrell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-stopsite [site_name]
#

. $ZOTONIC_SCRIPTS/helpers/zotonic_setup

require_zotonic_running

SITE=$1

if [ ! $SITE ]
then
	echo USAGE: $0 [site_name] 1>&2
else
	echo "Stopping site $SITE on zotonic $NODENAME@$NODEHOST"
	$ZOTONIC_CALL -a "z shell_stopsite [$SITE]" 
	echo
fi
