#!/usr/bin/env bash
#
# Copyright 2011 Arjan Scherpenisse
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-enablesite [site_name or directory]
#
source $ZOTONIC/src/scripts/helpers/zotonic_enabledisable


function enablesite {
    $ZOTONIC/bin/zotonic status>/dev/null && $ERL -noshell -pa $PA -name ${SNAME}_enable@$HOSTNAME -s z_sites_manager restart $1 -s init stop
}

SITE=$1

if [ ! $SITE ]; then
    echo USAGE: $0 [site_name or directory] [source_server] 1>&2
    exit 1;
fi

cd $ZOTONIC
if [ "${SITE:0:1}" = "/" -o -d $SITE ]; then

    enablesitedir $SITE
    enablesite `basename $SITE`
    echo "ok."
    
else
    if [ -e "priv/sites/$SITE" ]; then
        SITEDIR=$(cd priv/sites/$SITE; pwd -P);
        enablesitedir $SITEDIR
    else
        # check if in sites-disabled folder
        if [ -e "priv/sites-disabled/$SITE" ]; then
            mv "priv/sites-disabled/$SITE" "priv/sites/"
            enablesite $SITE
            echo "ok"
        fi
    fi
fi
