#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic-restartsite [site_name]
%%

-export([main/1]).

-include("zotonic_escript_helper.hrl").

main([Site]) ->
    zotonic_setup:require_zotonic_running(),
    case Site of
         " " ->
             io:format("USAGE: ~s [site_name] ~n", [escript:script_name()]);
        _ ->
            SitePath = ?ZOTONIC ++ "/user/sites/" ++ Site,
            case filelib:is_dir(SitePath) of
                true   ->
                    io:format("Restarting site ~s on zotonic ~s@~s", [Site, ?NODENAME, ?NODEHOST]),
                    z_sites_manager:restart(Site);
                false ->
                    io:format("Site not found. Please make sure zotonic site exist.")
            end
    end.
