#!/usr/bin/env bash
#
# Copyright 2011 Maas-Maarten Zeeman
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# usage zotonic-etop -sort [memory|msg_q|reductions] -accumulate [true|false]
#    See also: http://www.erlang.org/doc/man/etop.html
#

CONSOLE_LINES=`tput lines`
LINES=$(($CONSOLE_LINES - 11))

$ERL -name zotonic_etop@$HOSTNAME -hidden -s etop -s erlang halt -lines $LINES -tracing off -output text -node $SNAME@$HOSTNAME $@
