#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic runtests
%%

-export([main/1]).

-include("zotonic_escript_helper.hrl").

-define(ZOTONIC_PORT, 8040).
-define(ZOTONIC_LISTEN_PORT, 8040).
-define(ZOTONIC_PORT_SSL, 8043).
-define(ZOTONIC_SSL_LISTEN_PORT, 8043).
-define(ZOTONIC_SMTP_BOUNCE_PORT, 2535).
-define(EBIN_DIR, ?ZOTONIC ++ "/_build/default/lib/zotonic/ebin").

main([]) ->
    erlang:error(not_implemented).
