
../../lib/admin-bootstrap3/css/bootstrap.css: bootstrap-sass-3.4.1/assets/stylesheets/* \
	bootstrap-sass-3.4.1/assets/stylesheets/bootstrap/* \
	admin-bootstrap.scss \
	zotonic/*
	sass admin-bootstrap.scss ../../lib/css/admin-bootstrap3.css
