FROM erlang:27.3.4

# Start this image using ./start-docker.sh

# This Docker image is used to run Zotonic inside the container
# in conjunction with a postgresql container.
# All Zotonic sources, configuration and other data is stored outside the
# container(s). Check the docker-compose.yml file for details.

ENV SHELL="/bin/sh"

WORKDIR /opt/zotonic


# Install Zotonic runtime dependencies.
# Git is necessary because rebar3 compile requires git.
RUN apt-get update
RUN apt-get -y install build-essential libcap2-bin libssl-dev automake autoconf \
        ncurses-dev zlib1g-dev git postgresql postgresql-client curl gettext \
        inotify-tools libnotify-bin clamav clamav-daemon ghostscript file \
        imagemagick ffmpeg xvfb wkhtmltopdf sass less vim \
        gosu dumb-init

# Max inotify files setting
RUN echo "fs.inotify.max_user_watches=10000" > /etc/sysctl.d/40-max-user-watches.conf

# Enable ImageMagick PDF rendering
RUN sed -i 's/^.*pattern="PDF".*$/<!-- &1 -->/g' /etc/ImageMagick-6/policy.xml

COPY docker/docker-entrypoint.sh /opt/zotonic-docker/docker-entrypoint.sh

VOLUME /opt/zotonic

EXPOSE 8000 8443

# Use dumb-init to reap zombies, catch signals, and all the other stuff pid 1 should do.
ENTRYPOINT ["/usr/bin/dumb-init", "-c", "--", "/opt/zotonic-docker/docker-entrypoint.sh"]

CMD ["/bin/bash"]
