#!/usr/bin/env escript
%%
%% @author M, <tantemelki@gmail.com>
%% @copyright 2017
%%
%% Licensed under the Apache License, Version 2.0 (the "License");
%% you may not use this file except in compliance with the License.
%% You may obtain a copy of the License at
%%
%%	 http://www.apache.org/licenses/LICENSE-2.0
%%
%% Unless required by applicable law or agreed to in writing, software
%% distributed under the License is distributed on an "AS IS" BASIS,
%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%% See the License for the specific language governing permissions and
%% limitations under the License.

%%
%% usage zotonic generate-edoc
%%

-export([require_zotonic_running/0,
    require_zotonic_not_running/0,
    major_version/0,
    minor_version/0,
    find_enabled_sites/0,
    find_config/0,
    consult_config/0,
    find_config_arg/0,
    get_user_modules_dir/0,
    get_user_ebin_dir/0,
    main/1]).

-include("zotonic_escript_helper.hrl").

main(_Arg) ->
    erlang:error(not_implemented).


require_zotonic_running() ->
    case net_adm:ping(?NODENAME) of
        ping ->
            halt();
        else ->
            io:format("Failed to connect to ~s@~s", [?NODENAME, ?NODEHOST]),
            io:format("Zotonic is not running. You need to start Zotonic to use this command."),
            halt(0)
    end.


require_zotonic_not_running() ->
    case net_adm:ping(?NODENAME) of
          ping ->
              io:format("Zotonic is already running as ~s@~s", [?NODENAME, ?NODEHOST]),
              io:format("You cannot start two Zotonic instances with the same node name.")
    end.

major_version() ->
    erlang:error(not_implemented).

minor_version() ->
    erlang:error(not_implemented).

find_enabled_sites() ->
    erlang:error(not_implemented).

find_config() ->
    erlang:error(not_implemented).

consult_config() ->
    erlang:error(not_implemented).

find_config_arg() ->
    erlang:error(not_implemented).

get_user_modules_dir() ->
    erlang:error(not_implemented).

get_user_ebin_dir() ->
    erlang:error(not_implemented).
