{% extends "admin_edit_widget_std.tpl" %}

{# editing 2FA #}

{% block widget_title %}
{_ Two-factor authentication _}
<div class="widget-header-tools">
    <a href="#" class="z-btn-help do_dialog" data-dialog="{{
            %{
                title: _"Help about two-factor authentication",
                text: _"Two-factor authentication adds an extra check on log in. The user will need to enter a code which is generated by an app on their phone or in their password manager."
            }|escape
        }}" title="{_ Need more help? _}"></a>
</div>
{% endblock %}

{% block widget_show_minimized %}{{ not m.identity[id].is_user }}{% endblock %}

{% block widget_content %}

{% if m.acl.is_allowed.use.mod_admin_identity or id == m.acl.user %}
    <div class="form-group">
        <div id="auth2fa">
            {% live template="_auth2fa_user_actions.tpl" id=id topic=[ "bridge", "origin", "model", "identity", "event", id, "#" ] %}
        </div>
    </div>
{% endif %}

{% endblock %}
