#!/usr/bin/env bash

# Pass url to release file to download, something like:
# $ ./update-bootstrap https://github.com/twbs/bootstrap/releases/download/v3.3.5/bootstrap-3.3.5-dist.zip

cd `dirname $0`/../lib
rm -rf bootstrap
wget $1 -O bootstrap.zip
unzip bootstrap.zip -d .
rm bootstrap.zip
mv bootstrap* bootstrap
cd bootstrap/css
# replace relative urls to fonts with absolute ones
sed 's/..\/fonts/\/lib\/bootstrap\/fonts/g' bootstrap.css > bootstrap-tmp1.css
sed 's/..\/fonts/\/lib\/bootstrap\/fonts/g' bootstrap.min.css > bootstrap.min-tmp1.css
# replace sourceMappingURL to prevent it loading the sourcemap
sed 's/\#\ sourceMappingURL/ sourceMappingURL/g' bootstrap-tmp1.css > bootstrap-tmp2.css
# cleanup
mv bootstrap-tmp1.css bootstrap.css
mv bootstrap.min-tmp1.css bootstrap.min.css
rm bootstrap-tmp2.css