# Run documentation generation checks

name: Docs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    name: Docs on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [23]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: "doc/requirements.txt"
      - name: Compile
        run: make
      - name: EDocs
        run: make edocs
      - name: Erlang stubs
        run: make -C doc/ erlang-stubs
      - name: Html stubs
        run: make -C doc/ SPHINXOPTS='-nW' html-with-stubs
