# Run documentation generation checks

name: Docs 0.x

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ 0.x ]
  pull_request:
    branches: [ 0.x ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  linux:
    name: Docs on OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [22.3]
        os: [ubuntu-20.04]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install pip
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
      - run: pip install -r doc/requirements.txt --break-system-packages
      - name: Docs
        run: |
          make -C doc/ stubs
          make -C doc/ SPHINXOPTS='-nW' html
